name: Release
on:
  workflow_dispatch:
  push:
    paths:
      - .github/.version
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .version file
        id: version
        run: echo "version=$(cat .github/.version)" >> $GITHUB_OUTPUT
      - name: change version numbers
        run: sed -i "s|0.0.0|"$(cat .github/.version)"|g" widget.js
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          title: ${{ steps.version.outputs.version }}
          automatic_release_tag: ${{ steps.version.outputs.version }}
          files: |
            widget.js
